### ISSUE TITLE
'Disassembly' object has not attribute 'addr_to_func'

### ISSUE THREAD

**Issue by unboxedtype** [b-mueller/laser-ethereum#42]
Hello!
I will appreciate any help regarding the following issue.
1) I have installed laser-ethereum (0.17.12) and mythril (0.19.3) using pip3 install --user
2) Inside python3, I execute your example given in README.md for my contract.
3) Everything runs smoothly, until I execute laser.sym_exec(address). I get:

```
>>> laser.sym_exec(address)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shishkin/.local/lib/python3.6/site-packages/laser/ethereum/svm.py", line 265, in sym_exec                                 
    node = self._sym_exec(gblState)
  File "/home/shishkin/.local/lib/python3.6/site-packages/laser/ethereum/svm.py", line 285, in _sym_exec                                
    if start_addr in disassembly.addr_to_func:
AttributeError: 'Disassembly' object has no attribute 'addr_to_func'
```
Before going deep into Laser sources, I would like to ask your help regarding this.
Maybe there is a fast solution.
Thanks!

**Comment by norhh** [comment]
Hi @unboxedtype , currently laser-ethereum is merged with mythril and so this repo is unmaintained, now you can just do `mythril.laser.<whatever you need>`,

**Comment by unboxedtype** [comment]
Thank you.
